name: "Setup PHP Environment"
description: "Sets up the PHP environment and installs dependencies"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Setup Dependencies
      uses: ./.github/action/setup-composer
